apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo-2
  namespace: anvarzhonov-ikb20-19-pr7
spec:
  containers:
  - name: cpu-demo-2-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "100"
      requests:
        cpu: "100"
    command: ["stress"]
    args:
    - cpus
    - "2"