apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: anvarzhonov-ikb20-19-pr7
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    command: ["stress"]
    args:
    - cpus
    - "2"