version: "3"
services:
    db:
        image: mysql:5.7
        container_name: db
        platform: linux/amd64
        command: --init-file /init.sql
        environment: 
            MYSQL_ROOT_PASSWORD: "password"
        ports:
            - "3306:3306"
        volumes:
            - './init.sql:/init.sql'
        restart: always 
    apache:
        build: ./
        container_name: apache
        volumes:
            - ./apache/log:/var/log/apache2
            - ./src:/var/www/html
            - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
        depends_on:
            - db
    nginx:
        image: nginx:1.13
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            -  ./src:/etc/nginx/html/
        depends_on:
            - apache

    redis:
        image: redis:6.2 
        restart: always 
        environment: 
        - ALLOW_EMPTY_PASSWORD=yes 
        ports: 
        - '6379:6379'
volumes:
    dbdata: